# Generated automatically from Makefile.in by configure.
CC = gcc
DEBUG = -g
CFLAGS = $(DEBUG) -O3 -fpic -shared -DHPUX_SOURCE -I/opt/ncurses/include
LDFLAGS = -shared

OBJECTS = countdown background alarms

all: $(OBJECTS)
clean:
	rm $(OBJECTS)

